//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager =>
            resourceMan ??= new global::System.Resources.ResourceManager("FriishProduce.Properties.Resources", typeof(Resources).Assembly);
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get => resourceCulture; set => resourceCulture = value;
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Icon brick =>
            (System.Drawing.Icon) ResourceManager.GetObject("brick", resourceCulture);
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap control_play =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("control_play", resourceCulture);
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap control_stop =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("control_stop", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cross =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("cross", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Database =>
            (byte[]) ResourceManager.GetObject("Database", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] English =>
            (byte[]) ResourceManager.GetObject("English", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_eu =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("flag_eu", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_eu50 =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("flag_eu50", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_eu60 =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("flag_eu60", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_jp =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("flag_jp", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_kr =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("flag_kr", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_us =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("flag_us", resourceCulture);
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Font => (byte[]) ResourceManager.GetObject("Font", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap information =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("information", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loading =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("loading", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("logo", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mapping_cc =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("mapping_cc", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mapping_gc =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("mapping_gc", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mapping_wiiremh =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("mapping_wiiremh", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mapping_wiiremv =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("mapping_wiiremv", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NeoGeo_VC1 => (byte[]) ResourceManager.GetObject("NeoGeo_VC1", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NeoGeo_VC2 => (byte[]) ResourceManager.GetObject("NeoGeo_VC2", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NeoGeo_VC3 => (byte[]) ResourceManager.GetObject("NeoGeo_VC3", resourceCulture);
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_white_cd =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("page_white_cd", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warn_reg_ico =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("warn_reg_ico", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_white_flash =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("page_white_flash", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_white_zip =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("page_white_zip", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap retroarch =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("retroarch", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap retroarch_w =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("retroarch_w", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap screen_nes =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("screen_nes", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap screen_smd =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("screen_smd", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap screen_sms =>
            (System.Drawing.Bitmap) ResourceManager.GetObject("screen_sms", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Sound_WiiVC => ResourceManager.GetStream("Sound_WiiVC", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] StaticBase => (byte[]) ResourceManager.GetObject("StaticBase", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tick => (System.Drawing.Bitmap) ResourceManager.GetObject("tick", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tick_circle => (System.Drawing.Bitmap) ResourceManager.GetObject("tick_circle", resourceCulture);

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap x => (System.Drawing.Bitmap) ResourceManager.GetObject("x", resourceCulture);

    }
}
