//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriishProduce.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager =>
            resourceMan ??= new global::System.Resources.ResourceManager("FriishProduce.Properties.Resources", typeof(Resources).Assembly);
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get => resourceCulture; set => resourceCulture = value;
        }

        /// <summary>
        ///   Centralized method for fetching a ResourceManager object with safe casting
        /// </summary>
        public static T GetResource<T>(string name) where T : class {
            object resource;
            // Use GetStream for audio/binary resources
            if (typeof(T) == typeof(System.IO.UnmanagedMemoryStream))
                resource = ResourceManager.GetStream(name, resourceCulture);
            else // Use GetObject for everything else
                resource = ResourceManager.GetObject(name, resourceCulture);
            return resource as T ?? throw new InvalidOperationException($"Resource '{name}' cannot be found or is not a valid {typeof(T).Name}.");
        }

        /// <summary>
        ///   Simplified wrapped methods to look up a localized System.Drawing.Icon
        /// </summary>
        public static System.Drawing.Icon GetIcon(string name) => GetResource<System.Drawing.Icon>(name);

        /// <summary>
        ///   Simplified wrapped methods to look up a localized System.Drawing.Bitmap
        /// </summary>
        public static System.Drawing.Bitmap GetBitmap(string name) => GetResource<System.Drawing.Bitmap>(name);

        /// <summary>
        ///   Simplified wrapped methods to look up a localized System.Byte[]
        /// </summary>
        public static byte[] GetBytes(string name) => GetResource<byte[]>(name);

// =====================================================================================================================>
//                      Simplified type-specific resources using wrapper methods below
// =====================================================================================================================>

// Icon image resources
//
        /// <summary>The brick icon image</summary>
        public static System.Drawing.Icon brick => GetIcon("brick");

// Byte array resources
//
        public static byte[] Database => GetBytes("Database");

        public static byte[] English => GetBytes("English");

        public static byte[] Font => GetBytes("Font");

        public static byte[] FlashHBMPatch => GetBytes("hbm_patch");

        public static byte[] NeoGeo_VC1 => GetBytes("NeoGeo_VC1");

        public static byte[] NeoGeo_VC2 => GetBytes("NeoGeo_VC2");

        public static byte[] NeoGeo_VC3 => GetBytes("NeoGeo_VC3");

        public static byte[] StaticBase => GetBytes("StaticBase");

// Bitmap image resources
//
        /// <summary>The play control button bitmap image</summary>
        public static System.Drawing.Bitmap control_play => GetBitmap("control_play");

        /// <summary>The stop control button bitmap image</summary>
        public static System.Drawing.Bitmap control_stop => GetBitmap("control_stop");

        /// <summary>The cross button bitmap image</summary>
        public static System.Drawing.Bitmap cross => GetBitmap("cross");

        /// <summary>The EU flag bitmap image</summary>
        public static System.Drawing.Bitmap flag_eu => GetBitmap("flag_eu");

        /// <summary>The EU flag (50hz) bitmap image</summary>
        public static System.Drawing.Bitmap flag_eu50 => GetBitmap("flag_eu50");

        /// <summary>The EU flag (60hz) bitmap image</summary>
        public static System.Drawing.Bitmap flag_eu60 => GetBitmap("flag_eu60");

        /// <summary>The Japan flag bitmap image</summary>
        public static System.Drawing.Bitmap flag_jp => GetBitmap("flag_jp");

        /// <summary>The Korean flag bitmap image</summary>
        public static System.Drawing.Bitmap flag_kr => GetBitmap("flag_kr");

        /// <summary>The US flag bitmap image</summary>
        public static System.Drawing.Bitmap flag_us => GetBitmap("flag_us");

        /// <summary>The information icon bitmap image</summary>
        public static System.Drawing.Bitmap information => GetBitmap("information");

        /// <summary>The loading spinner bitmap image</summary>
        public static System.Drawing.Bitmap loading => GetBitmap("loading");

        /// <summary>The logo bitmap image</summary>
        public static System.Drawing.Bitmap logo => GetBitmap("logo");

        /// <summary>The Classic Controller mapping bitmap image</summary>
        public static System.Drawing.Bitmap mapping_cc => GetBitmap("mapping_cc");

        /// <summary>The GameCube mapping bitmap image</summary>
        public static System.Drawing.Bitmap mapping_gc => GetBitmap("mapping_gc");

        /// <summary>The *horizontal* Wii Remote mapping bitmap image</summary>
        public static System.Drawing.Bitmap mapping_wiiremh => GetBitmap("mapping_wiiremh");

        /// <summary>The *vertical* Wii Remote mapping bitmap image</summary>
        public static System.Drawing.Bitmap mapping_wiiremv => GetBitmap("mapping_wiiremv");
        
        /// <summary>The CD page bitmap image (select ROM)</summary>
        public static System.Drawing.Bitmap page_white_cd => GetBitmap("page_white_cd");

        /// <summary>The warning icon bitmap image</summary>
        public static System.Drawing.Bitmap warn_ico => GetBitmap("warn_ico");

        /// <summary>The Flash page bitmap image (select SWF)</summary>
        public static System.Drawing.Bitmap page_white_flash => GetBitmap("page_white_flash");

        /// <summary>The ZIP page bitmap image (select ZIP ROM archive)</summary>
        public static System.Drawing.Bitmap page_white_zip => GetBitmap("page_white_zip");

        /// <summary>The RetroArch logo bitmap image</summary>
        public static System.Drawing.Bitmap retroarch => GetBitmap("retroarch");

        /// <summary>The RetroArch (white) logo bitmap image</summary>
        public static System.Drawing.Bitmap retroarch_w => GetBitmap("retroarch_w");

        /// <summary>The Patch button bitmap image</summary>
        public static System.Drawing.Bitmap patch_go => GetBitmap("patch_go");

        /// <summary>The NES screenshot bitmap image</summary>
        public static System.Drawing.Bitmap screen_nes => GetBitmap("screen_nes");

        /// <summary>The Sega Mega Drive screenshot bitmap image</summary>
        public static System.Drawing.Bitmap screen_smd => GetBitmap("screen_smd");

        /// <summary>The Sega Master System screenshot bitmap image</summary>
        public static System.Drawing.Bitmap screen_sms => GetBitmap("screen_sms");

        public static System.Drawing.Bitmap tick => GetBitmap("tick");
        public static System.Drawing.Bitmap tick_circle => GetBitmap("tick_circle");
        public static System.Drawing.Bitmap x => GetBitmap("x");

        /// <summary>The Wii Virtual Console sound as an UnmanagedMemoryStream resource</summary>
        public static System.IO.UnmanagedMemoryStream Sound_WiiVC => GetResource<System.IO.UnmanagedMemoryStream>("Sound_WiiVC");
    }
}
